### ISSUE TITLE
CTT.cfg was not update to reflect the new ChopShop_SSP3 part

### ISSUE THREAD

**Issue by BararQ** [doktorjet/ChopShop#4]
So I ran into this problem in my Career game. I found that the CTT.cfg was not update to reflect the new ChopShop_SSP3 part. The SSP3 Mk3 (3.75m) part defaults to Advanced Electrics which comes a few tech nodes before the SSP2 Mk2 (2.5m) in Advanced Solar Tech. So SSP3 Mk3 (3.75m) will show before SSP2 Mk2 (2.5m). You can see this in the techtree when playing a career game.

I did check this today on new downloads of the ChopShop_0.11.1.zip Jan 31, 2018 3.72MB 1.3.1 game version from curseforge and also the Version 0.11.2 for 1.41 released on Spacedock 2018-03-11.

To fix, you just need to add in this line below into the CTT.cfg file in the ChopShop/ModuleManager folder.

@PART[ChopShop_SSP3]:NEEDS[CommunityTechTree]
{
@TechRequired = advSolarTech
}

**Comment by doktorjet** [comment]
Thank you for finding a lost one. 
Snapped to cuttingEdgeSolarTech (1000 point techtree node).
